POST http://localhost:3003/api/blogs/
    Content-Type: application/json

    {
        "title": "Test blog",
        "author": "Julio Murillo",
        "url": "https://myblog.com",
        "likes": 1500
    }

###
POST http://localhost:3003/api/blogs/
    Content-Type: application/json

    {
        "title": "Test blog 2",
        "author": "Kathy Canessa",
        "url": "https://herblog.com",
        "likes": 1800
    }

###
POST http://localhost:3003/api/blogs/
    Content-Type: application/json

    {
        "title": "Test blog X",
        "author": "Matias Murillo Canessa",
        "url": "https://hisblog.com/Matias",
        "likes": 1300
    }

###
POST http://localhost:3003/api/blogs/
    Content-Type: application/json

    {
        "title": "Test blog Y",
        "author": "Camila Murillo Canessa",
        "url": "https://theblog.com/Matias",
        "likes": 5300
    }

###
POST http://localhost:3003/api/blogs/
    Content-Type: application/json

    {
        "title": "Test blog W",
        "author": "Camila Murillo Canessa",
        "url": "https://theblog.com/CamiW",
        "likes": 7300
    }

###
POST http://localhost:3003/api/blogs/
    Content-Type: application/json

    {
        "title": "Test blog B",
        "author": "Julio Murillo Canessa",
        "url": "https://theblog.com/JulioB"
    }