POST http://localhost:3001/api/people/
    Content-Type: application/json

    {
        "name": "Julio Murillo",
        "number": "+506-61853237"
    }

###

POST http://localhost:3001/api/people/
    Content-Type: application/json

    {
        "number": "+506-77778888"
    }

###

POST http://localhost:3001/api/people/
    Content-Type: application/json

    {
        "name": "Catalina Canessa"
    }

###

POST http://localhost:3001/api/people/
    Content-Type: application/json

    {}

###

POST http://localhost:3001/api/people/
    Content-Type: application/json

    {
        "name": "Catalina Canessa",
        "number": "+506-77778888"
    }

###
POST http://localhost:3001/api/people/
    Content-Type: application/json

    {
        "name": "Catalina Canessa",
        "number": "+506 44444444"
    }

###
POST http://localhost:3001/api/people/
    Content-Type: application/json

    {
        "name": "W",
        "number": "+506 5555555"
    }
